# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-22 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180722_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 18, 13, 0, 251137, tzinfo=utc)),
        ),
    ]
